# This file relates to internal XMOS infrastructure and should be ignored by external users

lib_name: lib_awe
project: '{{lib_name}}'
title: '{{lib_name}}: AWE Core for xcore'
version: 1.0.1

documentation:
  exclude_patterns_path: doc/exclude_patterns.inc
  linkcheck_ignore_regex: ['.*github.com/xmos/lib_awe.*']
  root_doc: doc/rst/lib_awe.rst
  cognidox_part_number: XM-015096-UG
  doxygen_projects:
    lib_awe:
      doxyfile_path: doc/Doxyfile.inc
  pdfs:
    doc/rst/lib_awe.rst:
      pdf_title: '{{title}}'
      pdf_filename: '{{lib_name}}_v{{version}}'
    README.rst:
      pdf_title: '{{title}} (README)'
      pdf_filename: '{{lib_name}}_v{{version}}_readme'
      pdf_short: yes
software:
  cognidox_part_number: XM-015095-SM
