---
project: lib_awe
title: AWE Library for XMOS
version: 0.1.0

documentation:
  exclude_patterns_path: doc/exclude_patterns.inc
  doxygen_projects:
    lib_xcore_math:
      doxyfile_path: doc/Doxyfile.inc
  pdfs:
    doc/programming_guide/index:
      pdf_title: "{{title}} - Programming Guide"
      pdf_filename: "{{project}}_programming_guide_v{{version}}"
